
name: 'AutoCoder-Action'
description: '**Autocoder: A GitHub Action for Automated Code Generation with ChatGPT*

Autocoder is a GitHub Action designed to automate code generation by leveraging the power of OpenAI’s ChatGPT. This action allows developers to integrate AI-driven code generation seamlessly into their workflows, making it easier to generate boilerplate code, documentation, or even complex algorithms.
When triggered, Autocoder interacts with ChatGPT to generate code based on custom prompts provided by the user. It sends the prompt to the model, processes the response, and then writes the generated code into a new file or modifies an existing one in the repository. Autocoder can be set to run on specific branches or triggered manually through workflow dispatch events.
After generating the code, Autocoder creates a pull request (PR) with the changes, allowing the team to review the AI-generated code before merging it. This process ensures that the generated code undergoes proper review and testing, maintaining code quality.'
author: 'Pankaj'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true
  REPOSITORY:
    description: 'The repository to run the action on'
    required: true
  ISSUE_NUMBER:
    description: 'The issue number to generate code for'
    required: true
  OPENAI_API_KEY:
    description: 'OpenAI API key for ChatGPT'
    required: true
  SCRIPT_PATH:
    description: 'Path to the script that interacts with ChatGPT'
    required: true
    default: './scripts/script.sh'
  LABEL:
    description: 'The label to trigger the action'
    required: true
    default: 'autocoder-bot'
  commit_message:
    description: 'The commit message to use for committing the generated code'
    required: false
    default: 'feat: Add code generated by ChatGPT'
  branch_prefix:
    description: 'Prefix for the branch name that will be created'
    required: false
    default: 'autocoder-branch-'
  base_branch:
    description: 'The base branch for the pull request'
    required: false
    default: 'main'
  pr_title:
    description: 'The title for the pull request'
    required: false
    default: 'Code generated by ChatGPT'
  pr_body:
    description: 'The body content for the pull request'
    required: false
    default: 'This pull request contains changes auto-generated by ChatGPT based on issue contents.'
  pr_label:
    description: 'Label to assign to the pull request'
    required: false
    default: 'autocoder-bot'
  pr_reviewers:
    description: 'Comma-separated list of reviewers to request for the pull request'
    required: false
  pr_assignees:
    description: 'Comma-separated list of assignees for the pull request'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Make script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash
    - name: Run interaction script
      run: ${{ inputs.SCRIPT_PATH }} ${{ inputs.GITHUB_TOKEN }} ${{ inputs.REPOSITORY }} ${{ inputs.ISSUE_NUMBER }} ${{ inputs.OPENAI_API_KEY }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        REPOSITORY: ${{ inputs.REPOSITORY }}
        ISSUE_NUMBER: ${{ inputs.ISSUE_NUMBER }}
        OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "autocoder-bot"
        git add .
        git commit -m "Add code snippets from issue #${{ inputs.ISSUE_NUMBER }}" -a || echo "No changes to commit"
      shell: bash
    - name: Create pull request
      id: create-pr
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "Add code snippets from issue #${{ inputs.ISSUE_NUMBER }}"
        title: "Add code snippets from issue #${{ inputs.ISSUE_NUMBER }}"
        body: |
          This pull request adds code snippets from issue #${{ inputs.ISSUE_NUMBER }}.
        branch: "autocoder-branch-${{ inputs.ISSUE_NUMBER }}"
        base: "main"
        labels: "autocoder-bot"
        reviewers: "autocoder-bot"
        assignees: "autocoder-bot"
