name: 'AutoCoder'
description: 'Code generation from GitHub issues using OpenAIs ChatGPT'
author: 'pankaj892'

inputs:
  GITHUB_TOKEN:
    description: 'Personal access token (PAT) used for GitHub API authentication. This token is required to create pull requests and handle other repository interactions.'
    required: true
  REPOSITORY:
    description: 'The repository where the action will be executed.'
    required: true
  ISSUE_NUMBER:
    description: 'The number of the issue that triggered the action.'
    required: true
  OPENAI_API_KEY:
    description: 'API key for OpenAI, enabling interactions with the ChatGPT service to generate code based on issue descriptions.'
    required: true
  SCRIPT_PATH:
    description: 'The path to the script that interacts with ChatGPT and generates code.'
    required: true
    default: ./scripts/script.sh
  LABEL:
    description: 'Allows users to customize the label that triggers the action.'
    required: true
    default: autocoder-bot

outputs:
  pull_request_url:
    description: 'The URL of the pull request that has been automatically created, containing the auto-generated code for review and potential merging.'

runs:
  using: 'composite'

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: make the script executable
      run: chmod +x ${{ inputs.SCRIPT_PATH }}
      shell: bash

    - name: Generate Code with ChatGPT
      id: generate_code
      run: ${{ inputs.SCRIPT_PATH }} ${{ inputs.GITHUB_TOKEN }} ${{ inputs.REPOSITORY }} ${{ inputs.ISSUE_NUMBER }} ${{ inputs.OPENAI_API_KEY }} > result.txt
      shell: bash
     
    # - name: Upload Artifact
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: autocoder-artifact
    #     path: result.txt

    # - name: Download Artifact
    #   uses: actions/download-artifact@v4
    #   with:
    #     name: autocoder-artifact
    #     path: .
    #     overwrite: true

    # - name: List Files
    #   run: ls -R ./autocoder-bot
    #   shell: bash

    - name: Commit files
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "autocoder-bot"
        git add .
        git commit -m "Add code snippets from issue #${{ github.event.issue.number }}" -a || echo "No changes to commit"
      shell: bash


    - name: Create pull request
      # if: success()
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        commit-message: "Add code snippets from issue #${{ github.event.issue.number }}"
        title: "Add code snippets from issue #${{ github.event.issue.number }}"
        body: |
            This pull request adds code snippets from issue #${{ github.event.issue.number }}.
        branch: "autocoder-branch-${{ github.event.issue.number }}"
        base: "main"
        labels: ${{ inputs.LABEL }}
        # reviewers: "autocoder-bot"
        # assignees: "autocoder-bot"

