name: AutoCoder Workflow

on:
  issues:
    types: [opened, reopened, labeled]
  # workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  interact-with-chatgpt:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'autocoder-bot')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Interact with ChatGPT
        # id: generate_code
        uses: pankaj892/Autocoder@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SCRIPT_PATH: "./scripts/script.sh"
          LABEL: "autocoder-bot"
