name: Say Hello Workflow

on:
  push:
    branches:
      - main

jobs:
  say_hello_job:
    runs-on: ubuntu-latest
    steps:
      - name: A job to say hello
        uses: actions/checkout@v4
      - name: Say Hello
        run: echo "Hello, world!"
